### ISSUE TITLE
Issue with concurrent queries

### ISSUE THREAD

**Issue by mkapoor17** [prestodb/presto#13305]
I've read a lot online about people having similar issues with concurrent queries with Presto and how having n concurrent queries and a query taking x seconds would take nx time. I'm really struggling to figure out how to optimize my Presto cluster to optimize for concurrent queries (1 per second). 

Context on the queries/metastore: We are using the hive connector and glue as our hive metastore. We query directly from s3. 

Right now I have 30 worker nodes and the coordinator/workers are using these settings:
```server:
  workers: 30
  worker:
    maxWorkerThreads: "32"
  node:
    environment: dev
    dataDir: /presto/etc/data
  log:
    presto:
      level: INFO
  config:
    path: /etc/presto
    http:
      port: 8080
    https:
      port: 8443
    query:
      maxMemory: "160GB"
      maxMemoryPerNode: "8GB" 
```

Based on my tests, it seems that only a few queries will run while others get stuck in the planning stage. I have confidence that this can be resolved. Athena is able to accomplish these concurrent queries in a reasonable time, I know its just a matter of tweaking settings, and/or adding more resources. Looking forward to hearing back.

**Comment by tooptoop4** [comment]
use 48 or 64CPU machines for workers
set task.max-worker-threads to 96
reduce task.concurrency to 8
try 60 workers instead of 30
increase maxMemoryPerNode
dedicate at least 30GB to coordinator heap and at least 16CPU

**Comment by mkapoor17** [comment]
@tooptoop4 Thanks for the suggestions I am seeing some improvements now but still work to be done. If there are about 5-10 concurrent queries, parallelism isn't affecting query latency but if there are about 20-60 in parallel, some queries hang and query latency is about 10 times worse. CPU utilization is still quite low. The workers have 7 CPUs and only about 1 CPU is being utilized. These are my settings. What do you recommend for better CPU util./memory util? No nodes are blocked, I disable reserved memory, and no queries are killed due to OOM. 

```
server:
  workers: 48
  worker:
    maxWorkerThreads: "96"
  concurrency: 8
  node:
    environment: dev
    dataDir: /presto/etc/data
  log:
    presto:
      level: INFO
  config:
    path: /etc/presto
    http:
      port: 8080
    https:
      port: 8443
    query:
      maxMemory: "160GB"
      maxMemoryPerNode: "10GB"
      maxTotalMemoryPerNode: "15GB"
  jvm:
    maxHeapSize: "35G"
    gcMethod:
      type: "UseG1GC"
      g1:
        heapRegionSize: "32M"
```
