### ISSUE TITLE
Suggestions for JMX exporter metrics for Presto 

### ISSUE THREAD

**Issue by mkapoor17** [prestodb/presto#13330]
I'm trying to get more metrics out of Presto using the JMX exporter similar to this PR: https://github.com/prometheus/jmx_exporter/pull/264

There is no documentation as to how to properly extract metrics and I'm having trouble getting useful metrics out of Presto. Can someone guide me or point me to documentation?

For example, I want to see active threads, how would I extract `com.facebook.presto.execution.executor:name=TaskExecutor.RunningSplits` and publish it? I also want `java.lang:type=Memory:HeapMemoryUsage.used` and `java.lang:type=Threading:ThreadCount` how should I publish these

This is my current configuration, which I copied verbatim from the PR I just posted above.

```
rules: 
    - pattern: "com.facebook.presto.hive<type=NamenodeStats, name=hive><>(.+AllTime.+): (.*)"
      name: "presto hive_namenodestats_$1"
      help: "Presto Hive: NameNodeStats $1"
      type: GAUGE
    - pattern: "com.facebook.presto.hive<type=NamenodeStats, name=hive><>(.+TotalCount.*): (.*)"
      name: "presto hive_namenodestats_$1"
      help: "Presto Hive: NameNodeStats $1"
      type: COUNTER
    - pattern: "com.facebook.presto.hive.metastore.thrift<type=ThriftHiveMetastore, name=hive><>(.+AllTime.+): (.*)"
      name: "presto hivemetastorestats_$1"
      help: "Presto Hive: Metastore Stats $1"
      type: GAUGE
    - pattern: "com.facebook.presto.hive.metastore.thrift<type=ThriftHiveMetastore, name=hive><>(.+TotalCount.*): (.*)"
      name: "presto hivemetastorestats_$1"
      help: "Presto Hive: Metastore Stats $1"
      type: COUNTER
    - pattern: "com.facebook.presto.execution<name=TaskManager><>(.+TotalCount.*): (.*)"
      name: "presto taskmanager_$1"
      help: "Presto: TaskManager Stats $1"
      type: COUNTER
    - pattern: "com.facebook.presto.failureDetector<name=HeartbeatFailureDetector><>ActiveCount: (.*)"
      name: "presto heartbeatdetector_activecount"
      help: "Presto: HeartBeat Detector ActiveCount"
      type: GAUGE
    - pattern: "com.facebook.presto.execution<name=QueryManager><>(.+AllTime.+): (.*)"
      name: "presto querymanager_$1"
      help: "Presto: QueryManager $1"
      type: GAUGE
    - pattern: "com.facebook.presto.execution<name=QueryManager><>(.+TotalCount.*): (.*)"
      name: "presto querymanager_$1"
      help: "Presto: QueryManager $1"
      type: COUNTER
    - pattern: "com.facebook.presto.execution<name=TaskExecutor><>(.*): (.*)"
      name: "presto taskexecutor_$1"
      help: "Presto: TaskExecutor Stats $1"
      type: COUNTER
    - pattern: "com.facebook.presto.memory<name=ClusterMemoryManager><>(.+): (.*)"
      name: "presto clustermemorymanager_$1"
      help: "Presto: ClusterMemoryManager $1"
      type: GAUGE
    - pattern: "com.facebook.presto.memory<type=ClusterMemoryPool, name=(.*)><>(.+): (.*)"
      name: "presto clustermemorypool_$1_$2"
      help: "Presto ClusterMemoryPool: $1 $2"
      type: GAUGE
```

**Comment by yen-von** [comment]
### Setup `jmx-exporter`
1. Where to run the exporter?
It's strongly encouraged to run the jmx exporter as Java Agent([see here for reason](https://github.com/prometheus/jmx_exporter#jmx-exporter)), so I won't cover scraping remote JMX target here

1. Download the jar file([their git repo](https://github.com/prometheus/jmx_exporter#jmx-exporter))

1. Config `jmx-exporter` as http server by add this line into `jvm.config`
```
-javaagent:[path to jmx_prometheus_javaagent jar file]=[port number]:[your exporter_config.yaml]
```
4. Start presto(`launcher start`) and verify that exporter is working by `curl 0.0.0.0:[port number]`. You should see something like
```
$ curl 0.0.0.0:8081
# HELP jmx_config_reload_failure_total Number of times configuration have failed to be reloaded.
# TYPE jmx_config_reload_failure_total counter
jmx_config_reload_failure_total 4.0
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 107.097495
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.56876096896E9
...
```

---
### How to write config.yaml
Easiest way is just leave the `config.yaml` file empty, by default, it will expose all the jmx metrics it scraped.
The downside, of course, is to have way too many unused metrics. 

It's tedious to write the filter patterns by yourself. Luckily, `jmx-exporter` print out the patterns in comment, so you can simply search and copy the metric pattern you want in unfiltered mode(using blank config file) and apply them later
```
...
                                                                               ↓↓↓↓↓↓↓↓↓↓↓↓↓ pattern string here ↓↓↓↓↓↓↓↓↓↓
# HELP java_lang_Memory_HeapMemoryUsage_used java.lang.management.MemoryUsage (java.lang<type=Memory><HeapMemoryUsage>used)
# TYPE java_lang_Memory_HeapMemoryUsage_used gauge
java_lang_Memory_HeapMemoryUsage_used 1.337296E8
...
```

the following config should cover the metrics you mentioned:
```
rules:
    - pattern: "presto.execution.executor<name=TaskExecutor><>RunningSplits"
      type: GAUGE
    - pattern: "java.lang<type=Threading><>ThreadCount"
      type: GAUGE
    - pattern: "java.lang<type=Memory><HeapMemoryUsage>used"
      type: GAUGE
```

For more advanced usage, check out their [official document](https://github.com/prometheus/jmx_exporter#configuration)
