### ISSUE TITLE
Runtime dependency requirements in presto native execution

### ISSUE THREAD

**Issue by Mionsz** [prestodb/presto#18497]
There is no well defined minimum required runtime dependency list for end user.
One can build the presto native execution in container with provided scripts but the end result will be about ~15Gb in size.

```yaml
presto-native-execution:
- {list-of-runtime-dependencies}
files-format:
    parquet:
    - {list-of-runtime-dependencies}
connectors:
    hdfs:
    - {list-of-runtime-dependencies}
    s3: 
    - {list-of-runtime-dependencies}
    tpch:
    - {list-of-runtime-dependencies}
```
@majetideepak
