### ISSUE TITLE
CircleCI deprecates Intel macOS in January 2024

### ISSUE THREAD

**Issue by nkaretnikov** [prestodb/presto#20959]
Presto uses this resource in `.circleci/continue_config.yml` to test presto-native-execution:

```
  macos-intel:
    macos:
      xcode: "14.3.0"
    resource_class: macos.x86.medium.gen2
```

It's marked as deprecated here:
https://circleci.com/docs/using-macos/

Announcement:
https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718

> Starting February 1, 2024 we will only offer Apple silicon-based macOS resources. As previously announced, we will be deprecating our Gen1 resources on 2 October 2023. We will also be deprecating our Dedicated Hosts at this time. In January 2024, we will deprecate our Gen2 resources, ending our support for all Intel-based macOS resources. **Jobs still calling these resource classes after this will fail with an Invalid resource class error.**
